import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';
import { format, parseISO } from 'date-fns';
import request from 'graphql-request';
import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AppProvider } from '../components/contexts/appContext';
import { IDEFooter } from '../components/ide-footer';
import { IDENavbar } from '../components/ide-navbar';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import {
	PageByPublicationDocument,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';

/* ── Helpers ─────────────────────────────────────────────────── */
function formatDate(dateString: string) {
	if (!dateString) return '';
	return format(parseISO(dateString), 'LLL d, yyyy');
}

/* ── Post component ──────────────────────────────────────────── */
type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
};

const PostView = ({ publication, post }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	useEmbeds({ enabled: canLoadEmbeds });

	if (post.hasLatexInPost) {
		setTimeout(() => {
			handleMathJax(true);
		}, 500);
	}

	useEffect(() => {
		if (!post) return;
		(async () => {
			await loadIframeResizer();
			triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
	}, []);

	const tags = post.tags ?? [];

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }} />
			</Head>

			<div className="blog-detail">
				<Link href="/blog" className="blog-detail__back">
					← back to blog
				</Link>

				<p className="blog-detail__meta-date">{formatDate(post.publishedAt)}</p>
				<h1 className="blog-detail__title">{post.title}</h1>

				{tags.length > 0 && (
					<ul className="blog-detail__tags">
						{tags.map((tag) => (
							<li key={tag.id} className="code-pill">
								#{tag.slug}
							</li>
						))}
					</ul>
				)}

				<MarkdownToHtml contentMarkdown={post.content.markdown} />
			</div>
		</>
	);
};

/* ── Page (static page) component ───────────────────────────── */
type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
};

const PageView = ({ page }: PageProps) => {
	return (
		<>
			<Head>
				<title>{page.title}</title>
			</Head>
			<div className="blog-detail">
				<Link href="/blog" className="blog-detail__back">
					← back
				</Link>
				<h1 className="blog-detail__title">{page.title}</h1>
				<MarkdownToHtml contentMarkdown={page.content.markdown} />
			</div>
		</>
	);
};

/* ── Main export ─────────────────────────────────────────────── */
type Props = PostProps | PageProps;

export default function PostOrPage(props: Props) {
	const maybePost = props.type === 'post' ? props.post : null;
	const publication = props.publication;

	return (
		<AppProvider publication={publication} post={maybePost}>
			<Layout>
				<IDENavbar />
				<div className="ide-container">
					{props.type === 'post' && <PostView {...props} />}
					{props.type === 'page' && <PageView {...props} />}
				</div>
				<IDEFooter />
			</Layout>
		</AppProvider>
	);
}

/* ── Data fetching ───────────────────────────────────────────── */
type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		return {
			props: {
				type: 'post',
				post: postData.publication.post,
				publication: postData.publication,
			},
			revalidate: 1,
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		return {
			props: {
				type: 'page',
				page: pageData.publication.staticPage,
				publication: pageData.publication,
			},
			revalidate: 1,
		};
	}

	return {
		notFound: true,
		revalidate: 1,
	};
};

export const getStaticPaths: GetStaticPaths = async () => {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => ({ params: { slug } })),
		fallback: 'blocking',
	};
};
